sys_prompt: |
  You are an AI specialized in the task of extracting entity-relation-entity triples from texts.

comment_symbol: ""

natlang_triple_layout: |
  {{"rel": {{"type": "{relation_type}"}}, "head": {{"text": "{entity_head}", "type": "{entity_type_head}"}}, "tail": {{"text": "{entity_tail}", "type": "{entity_type_tail}"}}}}

instruction: |
  Task: Extract a list of dictionaries in valid JSON format as follows: [{natlang_triple_layout}]

  ONLY generate the valid JSON, nothing else.

  The types of entities are: {ent_classes}

  The types of relations are: {relations}

icl_instruction: |
  Look at the examples below and then carry out the following indicated task.

rationale_prompt: |
  The candidate relations for this text are:\n{rels}\nThe candidate entities for this text are:\n{ents}